import { 
  Zap, 
  Shield, 
  Rocket, 
  Database, 
  Smartphone, 
  Code, 
  Users, 
  Globe,
  Lock,
  BarChart3,
  Palette,
  Cpu
} from 'lucide-react'

export const features = [
  {
    id: 'performance',
    title: 'Lightning Fast',
    description: 'Built with Next.js 15 and React 19 for unmatched performance and speed.',
    icon: Zap,
    color: 'from-yellow-500 to-orange-500',
    delay: 0,
  },
  {
    id: 'security',
    title: 'Fort Knox Secure',
    description: 'Enterprise-grade security with Supabase Auth and Row Level Security.',
    icon: Shield,
    color: 'from-green-500 to-emerald-500',
    delay: 0.1,
  },
  {
    id: 'scalable',
    title: 'Infinite Scale',
    description: 'Serverless architecture that scales from zero to millions of users.',
    icon: Rocket,
    color: 'from-purple-500 to-violet-500',
    delay: 0.2,
  },
  {
    id: 'database',
    title: 'Real-time DB',
    description: 'Live database updates with Supabase real-time subscriptions.',
    icon: Database,
    color: 'from-blue-500 to-cyan-500',
    delay: 0.3,
  },
  {
    id: 'mobile',
    title: 'Mobile First',
    description: 'Responsive design that looks perfect on every device and screen size.',
    icon: Smartphone,
    color: 'from-pink-500 to-rose-500',
    delay: 0.4,
  },
  {
    id: 'developer',
    title: 'Dev Paradise',
    description: 'TypeScript, hot reload, testing suite, and amazing developer experience.',
    icon: Code,
    color: 'from-indigo-500 to-purple-500',
    delay: 0.5,
  },
  {
    id: 'collaborative',
    title: 'Team Ready',
    description: 'Multi-user support with real-time collaboration features built-in.',
    icon: Users,
    color: 'from-teal-500 to-green-500',
    delay: 0.6,
  },
  {
    id: 'global',
    title: 'Global CDN',
    description: 'Edge-optimized deployment with worldwide content delivery network.',
    icon: Globe,
    color: 'from-orange-500 to-red-500',
    delay: 0.7,
  },
  {
    id: 'auth',
    title: 'Auth Master',
    description: 'Complete authentication with OAuth, magic links, and social providers.',
    icon: Lock,
    color: 'from-gray-500 to-slate-500',
    delay: 0.8,
  },
  {
    id: 'analytics',
    title: 'Data Insights',
    description: 'Built-in analytics and monitoring with Vercel Analytics integration.',
    icon: BarChart3,
    color: 'from-cyan-500 to-blue-500',
    delay: 0.9,
  },
  {
    id: 'design',
    title: 'Design System',
    description: 'Modern 2025 UI with brutalist elements and Y2K revival aesthetics.',
    icon: Palette,
    color: 'from-violet-500 to-purple-500',
    delay: 1.0,
  },
  {
    id: 'ai',
    title: 'AI Enhanced',
    description: 'Ready for AI integration with OpenAI API and modern ML workflows.',
    icon: Cpu,
    color: 'from-amber-500 to-orange-500',
    delay: 1.1,
  },
]